### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/identified-chimps-site#3]
I just noticed that the lists aren't updating, probably broke when the other primates were added?

Last modified date on the json is Fri, 10 Jul 2015 03:36:53 GMT

**Comment by chrissnyder** [comment]
Fixed!

**Comment by brianaharder** [comment]
The list still isn't auto updating, another update would be nice!

**Comment by chrissnyder** [comment]
Running the update again now. Really need to set this up as a recurring thing...

**Comment by brianaharder** [comment]
Thanks!  No big rush on this, I'll ask again in a few weeks if you haven't already gotten it up and running.

**Comment by jwidness** [comment]
Not to be a bother, but could we get another update when you get a chance?  Thanks so much : )

**Comment by jwidness** [comment]
Thanks!

**Comment by jwidness** [comment]
Sorry to bother again -- with crimson dew done, do you think we could get another update when you have a chance?  Super curious if any more chimp videos show up!

**Comment by jwidness** [comment]
Could you put another update through when you have a chance? Thanks!

**Comment by DarrenMcRoy** [comment]
Not sure I understand. What's the issue? Do we need to upload a new site?

**Comment by jwidness** [comment]
I don't know exactly what Chris normally does, but the identified chimps list -- http://www.chimpandsee.org/identified-chimps/ -- doesn't show any videos retired as chimp from dry lake.  My understanding is that it just doesn't run automatically and someone has to push an update.  Does that make sense?  I don't really know anything about the back end....

**Comment by chrissnyder** [comment]
Run https://github.com/zooniverse/identified-chimps-site/blob/master/bin/generate-lists.rb and ideally put it on a cron job. I just ran it manually as often as I remembered before.

**Comment by DarrenMcRoy** [comment]
Hey @astopy -- I think you're the new person handling Chimp & See data requests.

Could you please follow up on what Chris write above? Thanks!!

**Comment by adammcmaster** [comment]
Sure, I'll take a look at this on Monday.

**Comment by jwidness** [comment]
Thanks for looking into this -- is there anything I can help with?

**Comment by adammcmaster** [comment]
Sorry for the delay. I think this should be working again now, could you confirm @jwidness? I've set it up so that this should update automatically once per day from now on.

**Comment by jwidness** [comment]
It's definitely updated, thanks!
I'm getting weirdly long load times though for http://www.chimpandsee.org/identified-chimps/ -- the page itself loads, and the first couple lines of description are there, but the actual list of videos is taking a while.  I tried it again just now and timed it at 35 seconds.  Is it just me?

**Comment by adammcmaster** [comment]
Hmm, yeah the identified species list is pretty huge (over 18 MB) so it’ll be taking a while to download that. I’m not sure how big it was before, but presumably it’s only going to get bigger as time goes on.

**Comment by DarrenMcRoy** [comment]
Anything we can do to help reduce that load time? That site is fairly important for chimp ID...

**Comment by jwidness** [comment]
I thought at first that the large jump in size recently was because there are sooo many baboon videos now at Dry Lake, but it actually looks like somehow all the Frosty Sky videos are being listed both in the primate list, and in the chimp list.  I didn't count, but if true, that's ~130,000 items.  I think getting rid of those should reduce the load time quite a bit.

**Comment by adammcmaster** [comment]
Ah-ha! Yes, it looks like it was incorrectly counting a lot of those in both lists when they actually shouldn't have been in either. I've fixed that and the file is a lot smaller now.
